# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppCalculateCfunDcfun <- function(wavelengthsMatrix, rReglin, rCReglin) {
    .Call('_QuasarFitCuda_cppCalculateCfunDcfun', PACKAGE = 'QuasarFitCuda', wavelengthsMatrix, rReglin, rCReglin)
}

cppFixReglin <- function(cReglinVector, reglinVector) {
    .Call('_QuasarFitCuda_cppFixReglin', PACKAGE = 'QuasarFitCuda', cReglinVector, reglinVector)
}

cppCalculateContinuumMatrix <- function(wavelengthsMatrix, reglinVector) {
    .Call('_QuasarFitCuda_cppCalculateContinuumMatrix', PACKAGE = 'QuasarFitCuda', wavelengthsMatrix, reglinVector)
}

cppReduceContinuumChisq <- function(chisq, sizes) {
    .Call('_QuasarFitCuda_cppReduceContinuumChisq', PACKAGE = 'QuasarFitCuda', chisq, sizes)
}

cppExpandTemplate <- function(wavelengths, sizes, feWavelengths, feSpectrum, feFitParams) {
    .Call('_QuasarFitCuda_cppExpandTemplate', PACKAGE = 'QuasarFitCuda', wavelengths, sizes, feWavelengths, feSpectrum, feFitParams)
}

cppCalculateFeScaleRates <- function(spectrumsMatrix, templateMatrix, sizes, feFitParams) {
    .Call('_QuasarFitCuda_cppCalculateFeScaleRates', PACKAGE = 'QuasarFitCuda', spectrumsMatrix, templateMatrix, sizes, feFitParams)
}

cppCalculateFeReducesChisq <- function(spectrumsMatrix, templateMatrix, errorsMatrix, sizes) {
    .Call('_QuasarFitCuda_cppCalculateFeReducesChisq', PACKAGE = 'QuasarFitCuda', spectrumsMatrix, templateMatrix, errorsMatrix, sizes)
}

cppCountNInfSize <- function(inputMatrix) {
    .Call('_QuasarFitCuda_cppCountNInfSize', PACKAGE = 'QuasarFitCuda', inputMatrix)
}

cppCopyNInf <- function(inputMatrix, newHeight) {
    .Call('_QuasarFitCuda_cppCopyNInf', PACKAGE = 'QuasarFitCuda', inputMatrix, newHeight)
}

cppFilterWithValues <- function(wavelengthMatrix, spectrumMatrix, errorMatrix, sizes) {
    .Call('_QuasarFitCuda_cppFilterWithValues', PACKAGE = 'QuasarFitCuda', wavelengthMatrix, spectrumMatrix, errorMatrix, sizes)
}

cppFilterWithParagon <- function(paragonMatrix, aMatrix, bMatrix, sizes) {
    .Call('_QuasarFitCuda_cppFilterWithParagon', PACKAGE = 'QuasarFitCuda', paragonMatrix, aMatrix, bMatrix, sizes)
}

cppFilterWithWavelengthWindows <- function(wavelengthsMatrix, spectrumsMatrix, errorsMatrix, sizesVectorR, continuumWindowsVectorR) {
    .Call('_QuasarFitCuda_cppFilterWithWavelengthWindows', PACKAGE = 'QuasarFitCuda', wavelengthsMatrix, spectrumsMatrix, errorsMatrix, sizesVectorR, continuumWindowsVectorR)
}

cppMatrixLog10 <- function(inputMatrix) {
    .Call('_QuasarFitCuda_cppMatrixLog10', PACKAGE = 'QuasarFitCuda', inputMatrix)
}

cppMatrixAddScalar <- function(inputMatrix, scalar) {
    .Call('_QuasarFitCuda_cppMatrixAddScalar', PACKAGE = 'QuasarFitCuda', inputMatrix, scalar)
}

cppMatrixMinusMatrix <- function(inputMatrix, substrahendMatrix) {
    .Call('_QuasarFitCuda_cppMatrixMinusMatrix', PACKAGE = 'QuasarFitCuda', inputMatrix, substrahendMatrix)
}

cppMatrixDivideMatrix <- function(inputMatrix, divisorMatrix) {
    .Call('_QuasarFitCuda_cppMatrixDivideMatrix', PACKAGE = 'QuasarFitCuda', inputMatrix, divisorMatrix)
}

cppMatrixMultiplyCol <- function(inputMatrix, vector) {
    .Call('_QuasarFitCuda_cppMatrixMultiplyCol', PACKAGE = 'QuasarFitCuda', inputMatrix, vector)
}

cppMatrixTranspose <- function(inputMatrix) {
    .Call('_QuasarFitCuda_cppMatrixTranspose', PACKAGE = 'QuasarFitCuda', inputMatrix)
}

cppMovingAverage <- function(inputMatrix, colsSizeVector, windowSize) {
    .Call('_QuasarFitCuda_cppMovingAverage', PACKAGE = 'QuasarFitCuda', inputMatrix, colsSizeVector, windowSize)
}

cppGenerateWavelenghtMatrix <- function(params) {
    .Call('_QuasarFitCuda_cppGenerateWavelenghtMatrix', PACKAGE = 'QuasarFitCuda', params)
}

cppReglin <- function(x, y, sizes) {
    .Call('_QuasarFitCuda_cppReglin', PACKAGE = 'QuasarFitCuda', x, y, sizes)
}

cppReglinSimplified <- function(x, y, sizes) {
    .Call('_QuasarFitCuda_cppReglinSimplified', PACKAGE = 'QuasarFitCuda', x, y, sizes)
}

cppChisq <- function(x, y, e, sizes) {
    .Call('_QuasarFitCuda_cppChisq', PACKAGE = 'QuasarFitCuda', x, y, e, sizes)
}

